### ISSUE TITLE
Add support for using GATT with BLE peripheral

### ISSUE THREAD

**Issue by maks** [canonical/bluez.dart#10]
@robert-ancell sorry if this is silly question but I was looking through the API docs (and dart src) for this package and I couldn't figure out how to access the GATT functionality for BLE? 
Doing things like the [examples in this documentation](https://web.archive.org/web/20200731154234/https://core.docs.ubuntu.com/en/stacks/bluetooth/bluez/docs/reference/gatt-services), 

eg. the kind of workflow like:
* scan for devices
* connect to a device
* get connected devices list of Services, Charactertistics,
* listen for notifications from a specific characteristic

Essentially doing the kind of thing thats described say in this [blog post using bluetoothctl](https://budimir.cc/2020/02/27/ble-on-linux-with-bluetoothctl/)

Sorry if I've missed something obvious.

**Comment by robert-ancell** [comment]
I think we need new API for this, but definitely something worth doing!

**Comment by robert-ancell** [comment]
With #13 we should have sufficient support to do the simplest case of the workflow shown. I tested it by being able to poll the accelerometer of a micro:bit. Please open more issues if there are more features you need!

**Comment by maks** [comment]
That is simply awesome! thank you for implementing this so quickly @robert-ancell 👍🏻 🎉
