### ISSUE TITLE
Callback not called upon device discovery

### ISSUE THREAD

**Issue by Haochen7** [canonical/bluez.dart#19]
Thank you for your work on bluez.dart. Seems like the callback in the listen stream function is not called on Ubuntu 18.04 using the scan.dart example code. 

```dart
print('Searching for devices on ${adapter.name}...');
  for (var device in client.devices) {
    print('  ${device.name}');
    await adapter.removeDevice(device)
  }
  client.deviceAddedStream.listen((device) => print('  ${device.name}'));
```

Discovered devices are added to client.devices list but the print statement in the listen is not called upon discovery.

**Comment by robert-ancell** [comment]
Confirmed it's not working correctly here.

**Comment by robert-ancell** [comment]
Turns out it was a [regression in dbus.dart](https://github.com/canonical/dbus.dart/pull/143), thanks for finding that!
