### ISSUE TITLE
Shows as supporting iOS/MacOS/Windows on pub.dev

### ISSUE THREAD

**Issue by BlackXDragon** [canonical/bluez.dart#36]
I understand that windows doesn't support the BlueZ stack, however, pub.dev says this package apparently supports it. I've tested this package on Windows and got the error that it isn't supported.

Please add support for Windows or remove the Windows support tag from pub.dev.

**Comment by robert-ancell** [comment]
Couple of issues here:
- We don't currently have a means of specifying which platforms a package supports, so pub.dev is saying it works on all platforms since the package is pure Dart. Other packages that have native code show as working only on platforms they have code for.
- The bluez package should actually work fine on Windows, though it's not going to be useful there.
- If you develop an app that works on both Windows and Linux, then using the bluez package makes sense, and it's just at run time you would decide to use it.

So it really comes down to does the tag on pub.dev relate to a package being compilable on a given platform, or useful. @cbracken - do you have any recommendation on this?

**Comment by cbracken** [comment]
@stuartmorgan this may be up your alley -- is there any way of hinting platform support to pub when a package is pure Dart?

**Comment by BlackXDragon** [comment]
@robert-ancell , I don't quite understand in what sense you mean that the package should work fine on Windows but not be useful. Could you please explain it?

Also, when I try running the example given on Windows, the following is the error I get:
```
Unhandled exception:
SocketException: Connection failed (OS Error: Unix domain sockets are not available on this operating system.), address = /run/dbus/system_bus_socket, port = 0
```

**Comment by stuartmorgan** [comment]
> @stuartmorgan this may be up your alley -- is there any way of hinting platform support to pub when a package is pure Dart?

Not at the moment; that's https://github.com/dart-lang/pub/issues/2353. It's something that we've been discussing recently though as it is coming up more and more often.

**Comment by stuartmorgan** [comment]
(Well, no good way. I believe you *could* do it by making a no-op Linux-only plugin, and then having this package depend on it, but that would be cumbersome, and I believe have the unwanted side effect of making the package say that it's Flutter-only.)

**Comment by robert-ancell** [comment]
> @robert-ancell , I don't quite understand in what sense you mean that the package should work fine on Windows but not be useful. Could you please explain it?

This comes down to what the definition of "works" is :) In this case, the bluez code is working fine, but it's in the [dbus](https://pub.dev/packages/dbus) layer that it's failing to connect. We can't get Unix domain sockets to work on Windows (yet?), but D-Bus can use other transports (e.g. TCP/IP). So in theory, you could have set up D-Bus on Windows, and made a server that ran BlueZ, but this seems like a highly unlikely situation. So it *works*, but it's not really *useful* to anyone. All the documentation for bluez.dart mentions this is for Linux but the question is should pub.dev flag this for Windows or not (the issue @stuartmorgan linked to).

**Comment by robert-ancell** [comment]
Short answer to this bug is once https://github.com/dart-lang/pub/issues/2353 is resolved, we'll update bluez.dart to implement the recommended behaviour. This package is only expected to be useful on Linux, so that will likely result in us only listing that as the supported platform.

**Comment by BlackXDragon** [comment]
Oh, alright! Thanks for the clarification!

**Comment by pouryaomidi** [comment]
Hi @robert-ancell, I was also confused as @BlackXDragon that your package is also supported on Windows. I understand the issue with pure dart packages, but it would be nice to add a clarification in your readme. Your answer might technically sound correct but seems confusing when you say it 'works'. When you cannot run it out-of-the-box, it doesn't work.

**Comment by pouryaomidi** [comment]
Hi @robert-ancell, I would explicitly say: Windows is not supported and pub.dev is showing android/ios/macos/windows because of [this issue](https://github.com/canonical/bluez.dart/issues/36).

**Comment by robert-ancell** [comment]
[Update README](https://github.com/canonical/bluez.dart/pull/55).
