### ISSUE TITLE
Cannot call stop discovery

### ISSUE THREAD

**Issue by jeroen1602** [canonical/bluez.dart#52]
When calling the `stopDiscovery` method I get this error: `org.freedesktop.DBus.Error.UnknownMethod: Method "stopDiscovery" with signature "" on interface "org.bluez.Adapter1" doesn't exist`.

I think this is because of a typo. In the code it uses `StartDiscovery` for staring and `stopDiscovery` for stopping. As you can see `stop` doesn't start with  a capital letter.
https://github.com/canonical/bluez.dart/blob/85906228a7017e09cb7ab1c47a8fee8cbc578d1c/lib/src/bluez_client.dart#L90-L100

**Comment by robert-ancell** [comment]
Thanks for finding this @jeroen1602, it should be fixed in dbus.dart 0.7.0.
