### ISSUE TITLE
Include or document a link to the appearance property

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/bluez.dart#54]
After playing around with your awesome package in the settings project, I tried to find a string mapping for the appearance integer

Including the strings of the device types in the package is eventually problematic since there are so many languages but eventually a little info where to find the mapping could help :) 
Thanks in advance

![grafik](https://user-images.githubusercontent.com/15329494/126295381-5ceb27b4-9d90-4e1e-ac03-46423ed9e48f.png)

**Comment by robert-ancell** [comment]
The values are defined in the [Bluetooth specification](https://www.bluetooth.com/specifications/assigned-numbers/).
