### ISSUE TITLE
Monitor example only prints the devices one time

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/bluez.dart#65]
Using this example

https://github.com/canonical/bluez.dart/blob/main/example/monitor.dart

The devices are only printed out one time and then not anymore.

BUT when you open gnome control center parallel to your dart application the dart example prints out permanently.

The chance that I misunderstood this is pretty high, but shouldn't the stream give a stream of devices added/removed etc without GCC opened? 

![Peek 2021-10-14 13-59](https://user-images.githubusercontent.com/15329494/137313185-5dfbc3a6-658e-4822-9ee7-cb142f18d710.gif)

**Comment by robert-ancell** [comment]
It's hard to read the log from a screencast but when g-c-c is open it starts scanning on the Bluetooth adapter, which will generate calls to `onAdapterPropertiesChanged` (for the RSSI mostly). This is expected.

**Comment by Feichtmeier** [comment]
> 

Alright! How to trigger this "scan" from the dart side? :) Because without opening GCC I didn't manage to have a permanent, self-updating process of listing the devices more than one time

**Comment by robert-ancell** [comment]
You're probably looking for `BlueZAdapter.startDiscovery()`, see `example/scan.dart` for usage of this.
