### ISSUE TITLE
Can you Please try to add this to a true Cross platform package , like quick_blue

### ISSUE THREAD

**Issue by rohitsangwan01** [canonical/bluez.dart#79]
Hey , as title suggest , we dont really have true cross platform packages , there is one intresting package which currently supports
Windows , Mac , Android , Ios  , it would be great if you can add support of linux to that package, [quick_blue](https://pub.dev/packages/quick_blue)

**Comment by robert-ancell** [comment]
I've been looking at integrating with [flutter_reactive_ble](https://github.com/PhilipsHue/flutter_reactive_ble/pull/347) but not making good progress. Thanks for the hint about quick_blue.

**Comment by rohitsangwan01** [comment]
@robert-ancell ,i checked your flutter_reactive_ble fork , and used that code for implementing bluez in quick_blue, almost added all methods but , connections seems to be unstable

getting this error while connecting : org.bluez.Error.Failed: Software caused connection abort
and after few tries device got connected , but then disconnected again

**Comment by robert-ancell** [comment]
That's awesome! I'll have a look and see if I can reproduce the same issues.

Because Bluetooth can sometimes be hard to debug I've found the best method is to try using `bluetoothctl` to confirm that you can access the device under test reliably. You can also use d-feet or the `gdbus` command line tool to access the D-Bus API directly to confirm if the issue is in BlueZ or our usage of the API.

**Comment by robert-ancell** [comment]
There might be an issue here:
```dart
  void connect(String deviceId) async {
    await initBluez();
    final device = _getDeviceWithId(deviceId);
    if (device == null) {
      throw 'No such device $deviceId';
    } else {
      device.connect();
      _checkDeviceConnectionState(device);
    }
  }
```

You probably want to wait for the result of the connect call:
```
  Future<void> connect(String deviceId) async {
    await initBluez();
    final device = _getDeviceWithId(deviceId);
    if (device == null) {
      throw 'No such device $deviceId';
    } else {
      await device.connect();
      _checkDeviceConnectionState(device);
    }
  }
```

This also relies on the property changes being sent before the 'connect' completes. I think that should be the case but _checkDeviceConnectionState could potentially be using older data.

**Comment by rohitsangwan01** [comment]
@robert-ancell thanks , i will try this
Can we subscribe to characteristics ??
And get data as a stream

**Comment by robert-ancell** [comment]
I've just released bluez 0.7.8 which has support for subscription (use BlueZGattCharacteristic.startNotify and subscribe for changes to the 'Value` property. I'm working on getting data as a stream and MTU support at the moment.

**Comment by rohitsangwan01** [comment]
@robert-ancell  great will try with this update

**Comment by rohitsangwan01** [comment]
@robert-ancell are we suppose to read "Value" property in loop after using c.startNotify ??

**Comment by robert-ancell** [comment]
You want something like this:

```dart
characteristic.propertiesChanged.listen((names) {
  if (names.contains ('Value')) {
    handleValue(characteristic.value);
  }
});
handleValue(characteristic.value);
```

But we should really add a helper method to automatically make a stream for this.

**Comment by robert-ancell** [comment]
See the [BlueZ documentation](https://github.com/bluez/bluez/blob/master/doc/gatt-api.txt) for more information on the GATT API.

Over time I would like to see bluez.dart improved so that you don't have to refer to that, but for now that might be the easiest way to work out how to use the API.

**Comment by rohitsangwan01** [comment]
ohh i see , Got it, thanks for info
