### ISSUE TITLE
How to use bluez to act as bluetooth peripheral

### ISSUE THREAD

**Issue by delphi007** [canonical/bluez.dart#85]
The example seems mainly for central bluetooth device. I wonder whether it's possible to use blueZ plugin to implement or to say , emulate a bluetooth peripheral on linux?

**Comment by yanshouwang** [comment]
expect for this feature too.

**Comment by Frederik-VP** [comment]
here to. Would be great to see peripheral support over Dbus to BlueZ

**Comment by rohitsangwan01** [comment]
@RossComputerGuy can we also communicate with central devices, by defining our Services and Characteristics with Btle Advertisements, and handle read write operations
or we can just advertise for now ?

**Comment by RossComputerGuy** [comment]
@rohitsangwan01 Whatever is in the docs for the advertisement object is what is supported right now.
