### ISSUE TITLE
Filter by manufacturer data

### ISSUE THREAD

**Issue by fotiDim** [canonical/bluez.dart#94]
We have a bluetooth peripheral that does not advertise services nor has a static name, therefore we need to discover it by manufacturer data. [setDiscoveryFilter](https://pub.dev/documentation/bluez/latest/bluez/BlueZAdapter/setDiscoveryFilter.html) does not seem to support filtering by manufacturer data, though. Currently we are discovering all devices and filter in the app, but it would be nice if we could filter on the OS API level. Not sure if the corresponding API exists on Linux but other platforms like Android [have it](https://developer.android.com/reference/android/bluetooth/le/ScanFilter).

**Comment by robert-ancell** [comment]
The [BlueZ documentation](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/org.bluez.Adapter.rst#n71) doesn't seem to indicate this is supported - you would have to [contact the BlueZ developers](https://www.bluez.org/contact/). If they expose this API, then I'll happily add it to bluez.dart!
