### ISSUE TITLE
RastBerry pi4 device list problem

### ISSUE THREAD

**Issue by mskayali** [canonical/bluez.dart#95]
I cant list visible devices until I press on Manage Bluetooth devices >> Add Device from the  Linux UI. It seams that able to listen device list but cannot activate the Bluetooth Search method on native side.

**Comment by RossComputerGuy** [comment]
This doesn't have a graphical UI. You might want to look at reporting this issue to whatever tool you're using.

**Comment by mskayali** [comment]
Maybe I expressed it wrong. When I search for a device with Radtberry Linux, there is no response. If I start the library's search algorithm and log the listen process while simultaneously searching for a device from the Linux interface, device logs appear.

**Comment by robert-ancell** [comment]
This project is a wrapper library for accessing BlueZ from Dart/Flutter - @mskayali it looks like you have a problem with BlueZ itself, this will have to be reported at https://www.bluez.org/.
