### ISSUE TITLE
"Peripherial" typo causing "Failed to parse advertisement" error

### ISSUE THREAD

**Issue by Matt0912** [canonical/bluez.dart#98]
When trying to advertise as a peripheral device, I was getting the below error:

![image](https://github.com/canonical/bluez.dart/assets/52967964/136e4c9c-a09b-4bc6-806f-253db31b295a)

And using `dbus-monitor` found that the array being sent had the same typo from the `BlueZAdvertisementType` enum:

![image](https://github.com/canonical/bluez.dart/assets/52967964/870b9516-592d-4fbf-a6b2-e4caf6689231)

![image](https://github.com/canonical/bluez.dart/assets/52967964/3869fdc8-11d2-4f51-949a-4b837b2549ab)

Upon forking the repo and fixing this typo, the error was resolved and I could advertise as a peripheral device.

I'm surprised that nobody else has encountered this issue so let me know if I'm using the package wrong, if not I'm happy to open a PR to fix this.

**Comment by robert-ancell** [comment]
Looks like a bug, please open a PR :)
